name: Build and Release Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15, macos-15-intel]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller main.py --add-data assets:assets --add-data levels:levels

      - name: List files
        run: ls -R

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/main/main.exe dist/mazetest2-win.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/main dist/mazetest2-linux
          elif [[ "${{ matrix.os }}" == "macos-15" ]]; then
            mv dist/main dist/mazetest2-mac
          elif [[ "${{ matrix.os }}" == "macos-15-intel" ]]; then
            mv dist/main dist/mazetest2-mac-intel
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mazetest2-${{ matrix.os }}
          path: dist/*


  release:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: .

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Pack game files
        run: |
          mkdir mazetest2
          mkdir mazetest2-win
          mkdir mazetest2-linux
          mkdir mazetest2-mac
          mkdir mazetest2-mac-intel

          mv main/_internal/assets mazetest2-win/assets
          cp -r main/_internal/assets mazetest2-linux/assets
          cp -r main/_internal/assets mazetest2-mac/assets
          cp -r main/_internal/assets mazetest2-mac-intel/assets

          mv main/_internal/levels mazetest2/win/levels
          cp -r main/_internal/levels mazetest2-linux/levels
          cp -r main/_internal/levels mazetest2-mac/levels
          cp -r main/_internal/levels mazetest2-mac-intel/levels

          mv main/_internal mazetest2-win/_internal

          mv mazetest2-win.exe mazetest2-win/mazetest2-win.exe
          mv mazetest2-linux/main mazetest2-linux/mazetest2-linux
          mv mazetest2-mac/main mazetest2-mac/mazetest2-mac
          mv mazetest2-mac-intel/main mazetest2-mac-intel/mazetest2-mac-intel

          chmod +x mazetest2-mac/mazetest2-mac || true
          chmod +x mazetest2-mac-intel/mazetest2-mac-intel || true
          chmod +x mazetest2-linux/mazetest2-linux || true

          zip -r mazetest2-win.zip mazetest2-win/
          zip -r mazetest2-linux.zip mazetest2-linux/
          zip -r mazetest2-mac.zip mazetest2-mac/
          zip -r mazetset2-mac-intel.zip mazetest2-mac-intel/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mazetest2-*
          path: .

      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: MazeTest 2 ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          files: |
            ./mazetest2-win.zip
            ./mazetest2-mac.zip
            ./mazetest2-mac-intel.zip
            ./mazetest2-linux.zip
            
