name: Build and Release Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller main.py --add-data assets:assets --add-data levels:levels

      - name: List files (windows debugging)
        run: ls -R

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/main/main.exe dist/mazetest2-win.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/main dist/mazetest2-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/main dist/mazetest2-mac
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mazetest2-${{ matrix.os }}
          path: dist/*


  release:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Make files executable (Linux/Mac)
        run: chmod +x mazetest2-* || true

      - name: Pack game files
        run: |
          mv assets dist/assets
          mv levels dist/levels
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            Compress-Archive dist mazetest2-win.zip
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            zip -r mazetest2-linux.zip dist/
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            zip -r mazetest2-mac.zip dist/
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: MazeTest 2 ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          files: |
            mazetest2-linux.zip
            mazetest2-win.zip
            mazetest2-mac.zip
